---
#thanks to @flawless_retard
- name: 'Add http {{ ansible_serv }} configuration'
  template: src=../files/http.conf.j2 dest=/etc/{{ ansible_serv }}/sites-available/{{ service_name }}.http.conf owner=www-data group=www-data mode=0644
- name: 'Add http {{ ansible_serv }} symlink'
  file: src=/etc/{{ ansible_serv }}/sites-available/{{ service_name }}.http.conf dest=/etc/{{ ansible_serv }}/sites-enabled/{{ service_name }}.http owner=www-data group=www-data state=link
- name: 'Reload {{ ansible_serv }}'
  service: name={{ ansible serv }} state=reloaded
- name: 'Create certificate'
  shell: ./certbot-auto certonly --webroot --email {{ service_admin_email }} --agree-tos --webroot-path={{ webroot }} -d {{ service_host }};
  args:
    chdir: /opt/certbot
- name: 'Add https {{ ansible_serv }} configuration'
  template: src=..files/https.conf.j2 dest=/etc/{{ ansible_serv }}/sites-available/{{ service_name }}.https.conf owner=www-data group=www-data mode=0644
- name: 'Add external https {{ ansible_serv }} symlink'
  file: src=/etc/{{ ansible_serv }}/sites-available/{{ service_name }}.https.conf dest=/etc/{{ ansible_serv }}/sites-enabled/{{ service_name }}.https owner=www-data group=www-data state=link
- name: 'Reload {{ ansible_serv }}'
  service: name={{ ansible_serv }} state=reloaded
