---
#thanks to @flawless_retard
- name: Debian www structure prepared
  file:
    path: '{{ item.path }}'
    owner: '{{ item.owner | default(omit) }}'
    group: '{{ item.group | default(omit) }}'
    state: '{{ item.state | default("directory") }}'
  with_items:
    - { path: '/etc/{{ ansible_serv }}/sites-available' }
    - { path: '/etc/{{ ansible_serv }}/sites-enabled' }

- name: 'Add http {{ ansible_serv }} configuration'
  template:
    src: http.conf.j2
    dest: '/etc/{{ ansible_serv }}/sites-available/{{ service_name }}.http.conf'
    owner: '{{ www_owner | default(omit) }}'
    group: '{{ www_owner | default(omit) }}'
    mode: 0644

- name: 'Add {{ ansible_serv }} vhost symlink'
  file:
    src: '/etc/{{ ansible_serv }}/sites-available/{{ service_name }}.http.conf'
    dest: '/etc/{{ ansible_serv }}/sites-enabled/{{ service_name }}.http'
    owner: '{{ www_owner | default(omit) }}'
    group: '{{ www_group | default(omit) }}'
    state: link

#  file: src=/opt/certbot/certbot-auto dest=/certbot-auto  state=link

- name: 'Reload {{ ansible_serv }}'
  service:
    name: '{{ ansible_serv }}'
    state: reloaded

- name: 'Create certificate'
  shell: ./certbot-auto certonly --webroot --email {{ service_admin_email }} --agree-tos --webroot-path={{ webroot }} -d {{ service_host }} > ansible-certification.log;
  args: 
    chdir: /opt/certbot
    creates: ansible-certification.log
#  expect: 
#    responses:
#      (?i)ok: 'y'

- name: 'Add https {{ ansible_serv }} configuration'
  template: src=../files/https.conf.j2 dest=/etc/{{ ansible_serv }}/sites-available/{{ service_name }}.https.conf owner={{ ansible_owner }} group={{ ansible_owner }} mode=0644 

- name: 'Add external https {{ ansible_serv }} symlink'
  file: src=/etc/{{ ansible_serv }}/sites-available/{{ service_name }}.https.conf dest=/etc/{{ ansible_serv }}/sites-enabled/{{ service_name }}.https owner={{ ansible_owner }} group={{ ansible_owner }} state=link 

- name: 'Reload {{ ansible_serv }}'
  service: name={{ ansible_serv }} state=reloaded
# Auto-renew certificates and reload nginx

- name: Add crontab to renew certificates
  cron: minute="45" hour="3" weekday="1" job="/opt/certbot/certbot-auto renew >> /var/log/le_en-renew.log"

- name: Add crontab to reload server
  cron: minute="50" hour="3" weekday="1" job="/etc/init.d/{{ ansible_serv }} reload"
