---
#as template in part certification see also @flawless_retard and @geerlingui
#vars to /defaults and dynamic /vars in final version 

- name: 'Distro non-specific provision'
  include: provision.yml

- name: 'RedHat provision.'
  include: provision-RedHat.yml
  when: ansible_distribution == "CentOS"

- name: 'SUSE provision.'
  include: provision-SUSE.yml
  when: ansible_distribution == "openSUSE"

- name: Pexpect for unexpected
  pip:
    name: pexpect
    state: present

- name: 'Copying Webarchiv.cz'
  copy:
    src: webarchiv.cz
    dest: /var/www/
    owner: '{{ www_owner | default(omit) }}'
    group: '{{ www_group | default(omit) }}'
    mode: 0644

- name: 'Inluding certification for {{ ansible_serv }}'
  include: "certification.yml"
